// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnrMKWUXZCfunnzawSP7RY43FWikIaGHw',
    appId: '1:138150514355:android:a97a02668e7c214a302ac6',
    messagingSenderId: '138150514355',
    projectId: 'cyrpto-flow-app',
    storageBucket: 'cyrpto-flow-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsIPB8IkcdZH0CmQjdwn6kSkJWeI45cok',
    appId: '1:138150514355:ios:ceb02684208c309a302ac6',
    messagingSenderId: '138150514355',
    projectId: 'cyrpto-flow-app',
    storageBucket: 'cyrpto-flow-app.firebasestorage.app',
    androidClientId: '138150514355-s1440a2q9fpdmv4ke7qohv6rjhisnush.apps.googleusercontent.com',
    iosClientId: '138150514355-l6e94sa448rapr3r1kpkcev73eoa1jed.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyrptoFlowApp',
  );

}